export const MOCK_USERS = {
    'mock-user-1': {
        id: 'mock-user-1',
        name: 'Eng. Amélia Cossa',
        role: 'WORKER',
        profession_category: 'Eletricista Predial & Residencial',
        province: 'Maputo',
        city: 'Maputo',
        bairro: 'Sommerchield',
        is_verified: true,
        is_premium: true,
        profile_photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300',
        bio: 'Engenheira Eletrotécnica com mais de 7 anos de experiência em instalações prediais, manutenção preventiva e automação residencial em Maputo.',
        years_experience: 7,
        rating: 4.9,
        reviews_count: 18,
    },
    'mock-user-2': {
        id: 'mock-user-2',
        name: 'Construções Nhantumbo',
        role: 'EMPLOYER',
        profession_category: 'Construção Civil & Obras',
        province: 'Maputo',
        city: 'Matola',
        bairro: 'Matola Rio',
        is_verified: true,
        is_premium: false,
        profile_photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300',
        bio: 'Empresa especializada em construção de habitações, pintura fina, serralharia e reabilitação de infraestruturas.',
        rating: 4.8,
        reviews_count: 24,
    },
    'mock-user-3': {
        id: 'mock-user-3',
        name: 'Dra. Beatriz Mabunda',
        role: 'WORKER',
        profession_category: 'Contabilidade & Finanças',
        province: 'Sofala',
        city: 'Beira',
        bairro: 'Ponta Gêa',
        is_verified: true,
        is_premium: true,
        profile_photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300',
        bio: 'Consultora de Contabilidade e Auditoria para PMEs em Moçambique. Especialista em gestão fiscal (IRPS, IRPC, IVA) e submissões à AT.',
        years_experience: 10,
        rating: 5.0,
        reviews_count: 31,
    },
    'mock-user-4': {
        id: 'mock-user-4',
        name: 'Técnico Fernando Mucavele',
        role: 'WORKER',
        profession_category: 'Climatização & AC',
        province: 'Gaza',
        city: 'Xai-Xai',
        bairro: 'Praia de Xai-Xai',
        is_verified: false,
        is_premium: false,
        profile_photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300',
        bio: 'Técnico certificado em reparação e montagem de sistemas de ar condicionado residencial e comercial. Atendimento rápido em toda a província de Gaza.',
        years_experience: 5,
        rating: 4.7,
        reviews_count: 12,
    },
    'mock-user-5': {
        id: 'mock-user-5',
        name: 'Clínica Saúde & Vida',
        role: 'EMPLOYER',
        profession_category: 'Saúde & Enfermagem',
        province: 'Maputo',
        city: 'Maputo',
        bairro: 'Polana Cimento',
        is_verified: true,
        is_premium: true,
        profile_photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300',
        bio: 'Centro médico privado focado em prestação de cuidados de saúde humanizados e de excelência.',
        rating: 4.9,
        reviews_count: 42,
    },
    'mock-user-6': {
        id: 'mock-user-6',
        name: 'Mestre Gabriel Nhamposse',
        role: 'WORKER',
        profession_category: 'Carpintaria & Marcenaria',
        province: 'Nampula',
        city: 'Nampula',
        bairro: 'Muhala',
        is_verified: true,
        is_premium: false,
        profile_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
        bio: 'Carpinteiro experiente na criação de mobiliário de luxo em madeira maciça (Chanfuta, Jambire e Umbila).',
        years_experience: 12,
        rating: 4.9,
        reviews_count: 29,
    },
    'mock-user-7': {
        id: 'mock-user-7',
        name: 'Serralharia Moçambique',
        role: 'WORKER',
        profession_category: 'Serralharia & Alumínio',
        province: 'Manica',
        city: 'Chimoio',
        bairro: 'Centro',
        is_verified: true,
        is_premium: true,
        profile_photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300',
        bio: 'Especialistas em estruturas metálicas, portões automáticos, portas de alumínio e vedações de alta segurança.',
        years_experience: 8,
        rating: 4.8,
        reviews_count: 15,
    },
    'mock-user-8': {
        id: 'mock-user-8',
        name: 'Dr. Isaac Tembe',
        role: 'WORKER',
        profession_category: 'Veterinária & Saúde Animal',
        province: 'Maputo',
        city: 'Matola',
        bairro: 'Tsalala',
        is_verified: true,
        is_premium: false,
        profile_photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300',
        bio: 'Médico Veterinário dedicado a serviços ao domicílio, vacinação e pequenos procedimentos cirúrgicos na Matola.',
        years_experience: 6,
        rating: 5.0,
        reviews_count: 22,
    },
    'mock-user-9': {
        id: 'mock-user-9',
        name: 'Catering Dona Rosa',
        role: 'WORKER',
        profession_category: 'Restauração & Eventos',
        province: 'Sofala',
        city: 'Beira',
        bairro: 'Macuti',
        is_verified: true,
        is_premium: true,
        profile_photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300',
        bio: 'Buffet de culinária tradicional e internacional para eventos, festas de casamento e encontros empresariais.',
        years_experience: 9,
        rating: 4.9,
        reviews_count: 36,
    },
    'mock-user-10': {
        id: 'mock-user-10',
        name: 'Pemba Tech Redes',
        role: 'WORKER',
        profession_category: 'Tecnologia & IT',
        province: 'Cabo Delgado',
        city: 'Pemba',
        bairro: 'Natite',
        is_verified: true,
        is_premium: false,
        profile_photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300',
        bio: 'Instalações de redes de dados, sistemas de segurança CCTV, servidores e suporte informático para empresas.',
        years_experience: 4,
        rating: 4.6,
        reviews_count: 11,
    },
    'mock-user-11': {
        id: 'mock-user-11',
        name: 'Oficina Auto Fast',
        role: 'EMPLOYER',
        profession_category: 'Mecânica Automóvel',
        province: 'Tete',
        city: 'Tete',
        bairro: 'Mateus Sansão Muthemba',
        is_verified: true,
        is_premium: false,
        profile_photo: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300',
        bio: 'Oficina mecânica especializada na reparação de viaturas 4x4, alinhamento, travões e eletrónica automóvel.',
        rating: 4.7,
        reviews_count: 19,
    },
    'mock-user-12': {
        id: 'mock-user-12',
        name: 'Arq. Sofia Mondlane',
        role: 'WORKER',
        profession_category: 'Arquitectura & Design',
        province: 'Maputo',
        city: 'Maputo',
        bairro: 'Coop',
        is_verified: true,
        is_premium: true,
        profile_photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300',
        bio: 'Arquitecta apaixonada por espaços modernos e sustentáveis. Projetos de raiz, maquetes 3D e licenciamento de habitações.',
        years_experience: 8,
        rating: 4.9,
        reviews_count: 27,
    },
    'mock-user-13': {
        id: 'mock-user-13',
        name: 'Canalização Silva',
        role: 'WORKER',
        profession_category: 'Canalização & Hidráulica',
        province: 'Inhambane',
        city: 'Inhambane',
        bairro: 'Balane',
        is_verified: false,
        is_premium: false,
        profile_photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300',
        bio: 'Canalizador profissional com atendimento 24h para reparações urgentes, desentupimentos e instalação de bombas.',
        years_experience: 6,
        rating: 4.8,
        reviews_count: 14,
    }
};

export const MOCK_POSTS = [
    {
        id: 'mock-post-1',
        user_id: 'mock-user-1',
        is_mock: true,
        content: `Terminado com sucesso mais um projecto de reabilitação elétrica residencial no Bairro Sommerchield. Equipa focada na segurança e qualidade dos materiais! ⚡🔌\n\nPrecisa de serviços de eletricidade predial ou residencial em Maputo? Deixe a sua mensagem ou contacte pelo perfil!`,
        image_url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800',
        created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        likes_count: 14,
        comments_count: 2,
        liked_by: [],
        author: MOCK_USERS['mock-user-1'],
        city: 'Maputo',
        province: 'Maputo',
        comments: [
            {
                id: 'mock-comm-1',
                post_id: 'mock-post-1',
                user_id: 'mock-user-10',
                author: { id: 'mock-user-10', name: 'Carlos Sitoe', profile_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150' },
                content: 'Excelente trabalho, Eng. Amélia! Muito profissional.',
                created_at: new Date(Date.now() - 1.5 * 3600 * 1000).toISOString()
            },
            {
                id: 'mock-comm-2',
                post_id: 'mock-post-1',
                user_id: 'mock-user-11',
                author: { id: 'mock-user-11', name: 'Marta Langa', profile_photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150' },
                content: 'Fazem orçamentos sem compromisso na Matola?',
                created_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString()
            }
        ]
    },
    {
        id: 'mock-post-2',
        user_id: 'mock-user-2',
        is_mock: true,
        content: `Estamos a recrutar 2 Pintores Profissionais e 1 Pedreiro com experiência em acabamentos finos para obra na Matola Rio. Início imediato!\n\nInteressados enviem mensagem direta ou entrem em contacto através do KoneKta. 🛠️🏗️`,
        image_url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800',
        created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
        likes_count: 21,
        comments_count: 1,
        liked_by: [],
        author: MOCK_USERS['mock-user-2'],
        city: 'Matola',
        province: 'Maputo',
        comments: [
            {
                id: 'mock-comm-3',
                post_id: 'mock-post-2',
                user_id: 'mock-user-12',
                author: { id: 'mock-user-12', name: 'Mateus Macamo', profile_photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150' },
                content: 'Tenho 8 anos de experiência em acabamentos de luxo. Já enviei mensagem!',
                created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString()
            }
        ]
    },
    {
        id: 'mock-post-3',
        user_id: 'mock-user-3',
        is_mock: true,
        content: `Dica de Contabilidade para Pequenos Negócios em Moçambique: Mantenha sempre a organização do IVA e IRPS mensal para evitar multas desnecessárias da AT.\n\nDisponível para consultoria financeira e gestão contábil para PMEs! 📊📑`,
        image_url: null,
        created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
        likes_count: 38,
        comments_count: 1,
        liked_by: [],
        author: MOCK_USERS['mock-user-3'],
        city: 'Beira',
        province: 'Sofala',
        comments: [
            {
                id: 'mock-comm-4',
                post_id: 'mock-post-3',
                user_id: 'mock-user-13',
                author: { id: 'mock-user-13', name: 'João Mondlane', profile_photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150' },
                content: 'Dica valiosa! Muito obrigado Dra. Beatriz.',
                created_at: new Date(Date.now() - 10 * 3600 * 1000).toISOString()
            }
        ]
    },
    {
        id: 'mock-post-4',
        user_id: 'mock-user-4',
        is_mock: true,
        content: `Instalação e manutenção preventiva de sistemas de climatização (AC) em escritórios e residências. Trabalho limpo, rápido e com garantia em Xai-Xai. ❄️🔧`,
        image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800',
        created_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
        likes_count: 9,
        comments_count: 0,
        liked_by: [],
        author: MOCK_USERS['mock-user-4'],
        city: 'Xai-Xai',
        province: 'Gaza',
        comments: []
    },
    {
        id: 'mock-post-5',
        user_id: 'mock-user-5',
        is_mock: true,
        content: `Procuramos Enfermeira(o) Geral com inscrição ativa na Ordem dos Enfermeiros de Moçambique para turno de dia na Polana Cimento. Envie a sua candidatura direta pelo KoneKta. 🩺🏥`,
        image_url: null,
        created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        likes_count: 27,
        comments_count: 0,
        liked_by: [],
        author: MOCK_USERS['mock-user-5'],
        city: 'Maputo',
        province: 'Maputo',
        comments: []
    },
    {
        id: 'mock-post-6',
        user_id: 'mock-user-6',
        is_mock: true,
        content: `Projecto de mobília sob medida entregue em Nampula! Mesas de jantar em madeira de chanfuta com acabamento impecável. 🪵🪑\n\nAceitamos encomendas para residências e escritórios. Orçamentos grátis!`,
        image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800',
        created_at: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
        likes_count: 19,
        comments_count: 2,
        liked_by: [],
        author: MOCK_USERS['mock-user-6'],
        city: 'Nampula',
        province: 'Nampula',
        comments: []
    },
    {
        id: 'mock-post-7',
        user_id: 'mock-user-7',
        is_mock: true,
        content: `Fabricação e montagem de portões elétricos, vedação de alumínio e redes de proteção em Manica. 🚪⚙️\n\nGaranta a segurança da sua casa com os melhores preços da região em Chimoio!`,
        image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800',
        created_at: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
        likes_count: 15,
        comments_count: 1,
        liked_by: [],
        author: MOCK_USERS['mock-user-7'],
        city: 'Chimoio',
        province: 'Manica',
        comments: []
    },
    {
        id: 'mock-post-8',
        user_id: 'mock-user-8',
        is_mock: true,
        content: `Cuidados veterinários ao domicílio na Matola e Maputo. Vacinação, consultas de rotina e tratamentos para os seus animais de estimação. 🐕🐈\n\nAgende já a consulta do seu pet!`,
        image_url: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800',
        created_at: new Date(Date.now() - 42 * 3600 * 1000).toISOString(),
        likes_count: 32,
        comments_count: 3,
        liked_by: [],
        author: MOCK_USERS['mock-user-8'],
        city: 'Matola',
        province: 'Maputo',
        comments: []
    },
    {
        id: 'mock-post-9',
        user_id: 'mock-user-9',
        is_mock: true,
        content: `Serviço de buffet completo e bolos decorados para casamentos, aniversários e eventos corporativos na Beira. 🎂🎉\n\nFaça já a sua reserva para este fim de semana!`,
        image_url: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=800',
        created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
        likes_count: 45,
        comments_count: 6,
        liked_by: [],
        author: MOCK_USERS['mock-user-9'],
        city: 'Beira',
        province: 'Sofala',
        comments: []
    },
    {
        id: 'mock-post-10',
        user_id: 'mock-user-10',
        is_mock: true,
        content: `Instalação de câmaras de vigilância CCTV, redes Wi-Fi empresariais e manutenção de computadores em Pemba. 💻📹\n\nProteja o seu negócio com tecnologia de ponta em Cabo Delgado!`,
        image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800',
        created_at: new Date(Date.now() - 54 * 3600 * 1000).toISOString(),
        likes_count: 11,
        comments_count: 1,
        liked_by: [],
        author: MOCK_USERS['mock-user-10'],
        city: 'Pemba',
        province: 'Cabo Delgado',
        comments: []
    },
    {
        id: 'mock-post-11',
        user_id: 'mock-user-11',
        is_mock: true,
        content: `Diagnóstico computadorizado, revisão geral de travões e suspensão para viaturas 4x4 e ligeiras em Tete. 🚗🔧\n\nTrabalhamos com rapidez e garantia de peças de qualidade.`,
        image_url: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800',
        created_at: new Date(Date.now() - 60 * 3600 * 1000).toISOString(),
        likes_count: 22,
        comments_count: 2,
        liked_by: [],
        author: MOCK_USERS['mock-user-11'],
        city: 'Tete',
        province: 'Tete',
        comments: []
    },
    {
        id: 'mock-post-12',
        user_id: 'mock-user-12',
        is_mock: true,
        content: `Desenho de projectos arquitectónicos modernos, modelação 3D e licenciamento municipal em Maputo e Matola. 🏛️📐\n\nTransforme o seu sonho em realidade com projectos inovadores!`,
        image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
        created_at: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
        likes_count: 51,
        comments_count: 4,
        liked_by: [],
        author: MOCK_USERS['mock-user-12'],
        city: 'Maputo',
        province: 'Maputo',
        comments: []
    },
    {
        id: 'mock-post-13',
        user_id: 'mock-user-13',
        is_mock: true,
        content: `Detecção de fugas de água, montagem de bombas de água e sistemas de canalização para vivendas em Inhambane e Maxixe. 🚰💧\n\nAtendimento de urgência 24 horas!`,
        image_url: null,
        created_at: new Date(Date.now() - 84 * 3600 * 1000).toISOString(),
        likes_count: 17,
        comments_count: 1,
        liked_by: [],
        author: MOCK_USERS['mock-user-13'],
        city: 'Inhambane',
        province: 'Inhambane',
        comments: []
    }
];

export function getMockPostById(id) {
    return MOCK_POSTS.find(p => p.id === String(id)) || null;
}

export function getMockUserById(id) {
    return MOCK_USERS[String(id)] || null;
}
